### ISSUE TITLE
Code-block not detecting languages

### ISSUE THREAD

**Issue by Yokto13** [xigoi/xidoc#10]
Hi,

I noticed the following issue when using `code-block`: 

I have the following piece of code that I'd like to display in python formatting:
```
[code-block python;
	[raw
		X = np.arange(-10, 10, 1.5)
		Y = np.arange(-10, 10, 1.5)
		X, Y = np.meshgrid(X, Y)
	]
]
```

However, when I try to compile this in xidoc it gives me:
```
Unknown language for syntax highlighting: python
```

It used to work fine. But it broke after I reinstalled xidoc with the command
```
nimble install xidoc
```

I might have messed something up during the reinstall, my understanding of nimble is very limited. Also it works fine when I remove the `?language` specifier.

**Edit:**
The same problem is also with the example from the webpage:
```
[code-block javascript; [raw
const factorial = (n) => {
  let result = 1n;
  for (let i = 1; i <= n; i++) {
    result *= BigInt(i);
  }
  return result;
}
]]
```
also fails so it's not just python-highlighting issue.

**Comment by xigoi** [comment]
Thank you, this was an issue with the syntax highlighting definitions being loaded from a directory relative to the current directory when compiling, so it would break if you installed xidoc from outside the xidoc repository. Should be fixed now.

**Comment by Yokto13** [comment]
Thank you. Now it works as expected.
