### ISSUE TITLE
Table of Contents in "commands.xd"

### ISSUE THREAD

**Issue by celtic-coder** [xigoi/xidoc#3]
Hi Adam (@xigoi),

The [Commands](http://xidoc.nim.town/commands.html) reference document is quite long. Might it be possible to include a Table of Contents (based on the "h2" headings), like the following:

* Introduction
* Top-level commands
* HTML commands
* CSS commands
* Math commands

This will give the reader an overview of the content before they get caught up in the technical details. The document is well-written and comprehensive. Therefore, I believe, that a Table of Contents would make it easier to approach for a new user.

Kind Regards,
Liam

**Comment by xigoi** [comment]
Sounds like a good idea! I'm planning to add a facility for generating a table of contents, but I'm not sure how to fit it into the single-pass nature of xidoc. I might add one manually though.

**Comment by celtic-coder** [comment]
OK, thanks!

**Comment by xigoi** [comment]
After a year of head-scratching, I've finally come up with a good way to implement a table of contents command. As a consequence, there is now a table of contents in the command reference.

**Comment by celtic-coder** [comment]
Great work, thanks! 👍
