### ISSUE TITLE
Suggestion: Practical Markup Language (PML) and HastyScribe

### ISSUE THREAD

**Issue by celtic-coder** [xigoi/xidoc#4]
Hi Adam (@xigoi),

When you have the opportunity, perhaps you could consider the following GitHub repos for possible ideas that could be included in XiDoc?

### Practical Markup Language (PML)

I'm guessing that one of the influences on your markup syntax is from [Arturo](https://github.com/arturo-lang/arturo), where it uses square brackets to delimit blocks.

Interestingly, PML is similar, as seen on the [home page](https://www.pml-lang.dev/index.html). The rationale behind the markup language is explained in the [FAQ](https://www.pml-lang.dev/about/faq.html) and the [User Manual](https://www.pml-lang.dev/docs/user_manual/index.html) gives a quick overview of the language.

I have used PML in the past and when I came across XiDoc, I was struck by the similarities. Perhaps there might be some ideas that you might be able to glean and add to your own markup?

### HastyScribe

Like Aturo and XiDoc, [HastyScribe](https://github.com/h3rald/hastyscribe) is written in Nim. It takes Markdown (with some modifications) and creates a standalone self-contained HTML output. One of the things you might want to look at is how HastyScribe embeds all images in the HTML output. The [Introduction to HastyScribe](https://h3rald.com/articles/hastyscribe/) again might give you some ideas.

I am only beginning to look at XiDoc and I trust that these suggestions will help either generate some ideas or else point you towards some code that you can incorporate into your own markup.

Kind Regards,
Liam

**Comment by xigoi** [comment]
Wow! PML looks very similar to xidoc! It's a shame I didn't know about it before…

I do know about HastyScribe and it's one of the projects that gave me the idea to make my own markup language.

**Comment by celtic-coder** [comment]
Well, at least there might be "food for thought" for any future ideas!
