### ISSUE TITLE
Ordered lists

### ISSUE THREAD

**Issue by Yokto13** [xigoi/xidoc#6]
This is an idea for an enhancement. 

As far as I know there is no ordered list feature. However sometimes I find myself needing to write cookbook-like set of instructions that ought to be followed in a specific order. Here it would make sense to have it.

**Comment by xigoi** [comment]
[Done.](http://xidoc.nim.town/commands.html#ordered-list)

Should I add a contributing guide so that people can make trivial changes like this themselves?

**Comment by xigoi** [comment]
[Done.](http://xidoc.nim.town/commands.html#ordered-list)

Should I add a contributing guide so that people can make trivial changes like this themselves?

**Comment by Yokto13** [comment]
Yes! Sounds great.

Hope that I will be able to learn a little bit of nim during the summer so I can make similar trivial improvements. Having a guide might help
