### ISSUE TITLE
Given the frequency of bold and italic, shouldn't the commands be just 'b' and 'i'?

### ISSUE THREAD

**Issue by eugenesvk** [xigoi/xidoc#8]
Also, how to do a **_bold italic_** text?

**Comment by xigoi** [comment]
Actually, you should rarely specify text formatting directly, instead preferring to define semantic custom commands. So for example, if you want to highlight keywords in your document, you should do something like this:

```xidoc
[def kw; x; [bf [arg x]]]
[p The [kw mitochondria] is the [kw power house] of the cell.]
```

That way if you decide to change the formatting, you can do so with no effort. If you wanted the keywords to be red instead of bold, you could just change the first line to:

```xidoc
[def kw; x; [color red; [arg x]]]
```

When compiling to HTML, it's also better to use semantic tags like `<strong>` and `<em>`, though currently xidoc doesn't have portable ways to emit those.

And to answer your second question, you just do `[bf [it this]]`.

**Comment by eugenesvk** [comment]
Ok, so I can make a convenient rule myself by making `bi` bold+italic (or making `b` bold and `i` italic), that's a cool feature!

```
[def bi; x; [bf [it [arg x]]]]
[p bolditalic [bi mitochondria] is the [bi power house] of the cell.]
[def b; x; [bf [arg x]]]
[p bold [b mitochondria] is the [b power house] of the cell.]
[def i; x; [it [arg x]]]
[p italic [i mitochondria] is the [i power house] of the cell.]
```
Though I still don't understand the value of the less convenient and, in the case of `bf`, less intuitive abbreviations

**Comment by xigoi** [comment]
The abbreviations are taken directly from LaTeX, so “less intuitive” is subjective. The reason for choosing them is to discourage purely presentational markup.

**Comment by eugenesvk** [comment]
LaTeX is too unpopular to counter any argument re user intuition, most widespread interfaces use "b" for bold, so it's a more intuitive match

Anyway, the intentional complication is a rather unfortunate design choice, encouragement should be done via positive reinforcement rather than extra barriers

**Comment by xigoi** [comment]
> LaTeX is too unpopular to counter any argument re user intuition, most widespread interfaces use "b" for bold

Are you sure? In academia, there are many more people who know LaTeX than those who know HTML.

> encouragement should be done via positive reinforcement rather than extra barriers

Two characters for a command is hardly a barrier. Still less typing than in HTML.

**Comment by eugenesvk** [comment]
> Are you sure? In academia, there are many more people who know LaTeX than those who know HTML.

Why would you limit the scope to academia? (your "What can I do with xidoc" section doesn't imply such a limited audience)
And HTML isn't relevant either, the most common formatting association people (even those who'd write in markup) encounter are those __B__ and _I_ buttons in various interfaces, so `b` and `i` are the most intuitive command abbreviations vs `bf` and `it`

> Two characters for a command is hardly a barrier. Still less typing than in HTML

Then how would it discourage??? That's the only reason not to pick the best (shortest and most intuitive) option
